# Generated by Django 4.2.17 on 2024-12-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_delete_task'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
