# Generated by Django 4.2.17 on 2024-12-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projectmember_project_and_more'),
        ('task', '0002_delete_task'),
        ('comment', '0002_delete_comment'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
